project_id = "nrfketkwajzkmrlkvoyd"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 17

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://localhost:3000"

[functions.generate-recipes]
verify_jwt = true

[functions.generate-shopping-list]
verify_jwt = true


[functions.cakto-webhook]
enabled = true
verify_jwt = false
entrypoint = "./functions/cakto-webhook/index.ts"
