import { useState } from "react";
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle
} from "@/components/ui/sheet";
import { Button } from "@/components/ui/button";
import { useFriggo } from "@/contexts/FriggoContext";
import { useLanguage } from "@/contexts/LanguageContext";
import { Share2, Copy, MessageCircle, Mail, Check, QrCode } from "lucide-react";
import { toast } from "sonner";

interface ShareListProps {
  open: boolean;
  onClose: () => void;
}

export function ShareList({ open, onClose }: ShareListProps) {
  const { shoppingList } = useFriggo();
  const { language } = useLanguage();
  const [copied, setCopied] = useState(false);

  const labels = {
    "pt-BR": {
      title: "Compartilhar Lista",
      copy: "Copiar",
      copied: "Copiado!",
      moreOptions: "Mais opções",
      generateQR: "Gerar QR Code",
      qrSoon: "QR Code em breve!",
      listCopied: "Lista copiada!",
      errorCopy: "Não foi possível copiar",
      emptyList: "Lista de compras vazia",
      market: "Mercado",
      fair: "Feira",
      pharmacy: "Farmácia",
      generatedBy: "Gerado pelo Friggo",
      shoppingList: "Lista de Compras - Friggo"
    },
    en: {
      title: "Share List",
      copy: "Copy",
      copied: "Copied!",
      moreOptions: "More options",
      generateQR: "Generate QR Code",
      qrSoon: "QR Code coming soon!",
      listCopied: "List copied!",
      errorCopy: "Could not copy",
      emptyList: "Shopping list empty",
      market: "Market",
      fair: "Fair",
      pharmacy: "Pharmacy",
      generatedBy: "Generated by Friggo",
      shoppingList: "Shopping List - Friggo"
    },
    es: {
      title: "Compartir Lista",
      copy: "Copiar",
      copied: "¡Copiado!",
      moreOptions: "Más opciones",
      generateQR: "Generar QR Code",
      qrSoon: "¡QR Code próximamente!",
      listCopied: "¡Lista copiada!",
      errorCopy: "No se pudo copiar",
      emptyList: "Lista de compras vacía",
      market: "Mercado",
      fair: "Feria",
      pharmacy: "Farmacia",
      generatedBy: "Generado por Friggo",
      shoppingList: "Lista de Compras - Friggo"
    }
  };

  const l = labels[language];
  const pendingItems = shoppingList.filter((item) => !item.isCompleted);

  const generateListText = () => {
    if (pendingItems.length === 0) return l.emptyList;
    const marketItems = pendingItems.filter((i) => i.store === "market");
    const fairItems = pendingItems.filter((i) => i.store === "fair");
    const pharmacyItems = pendingItems.filter((i) => i.store === "pharmacy");
    let text = `🛒 *${l.shoppingList}*\n\n`;
    if (marketItems.length > 0) {
      text += `📦 *${l.market}:*\n`;
      marketItems.forEach((item) => {
        text += ` ☐ ${item.name} (${item.quantity} ${item.unit})\n`;
      });
      text += "\n";
    }
    if (fairItems.length > 0) {
      text += `🌿 *${l.fair}:*\n`;
      fairItems.forEach((item) => {
        text += ` ☐ ${item.name} (${item.quantity} ${item.unit})\n`;
      });
      text += "\n";
    }
    if (pharmacyItems.length > 0) {
      text += `💊 *${l.pharmacy}:*\n`;
      pharmacyItems.forEach((item) => {
        text += ` ☐ ${item.name} (${item.quantity} ${item.unit})\n`;
      });
    }
    text += `\n📱 ${l.generatedBy}`;
    return text;
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(generateListText());
      setCopied(true);
      toast.success(l.listCopied);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast.error(l.errorCopy);
    }
  };

  const handleWhatsApp = () => {
    window.open(
      `https://wa.me/?text=${encodeURIComponent(generateListText())}`,
      "_blank"
    );
  };
  const handleEmail = () => {
    window.open(
      `mailto:?subject=${encodeURIComponent(
        l.shoppingList
      )}&body=${encodeURIComponent(generateListText().replace(/\*/g, ""))}`,
      "_blank"
    );
  };
  const handleNativeShare = async () => {
    const { shareContent } = await import("@/lib/nativeShare");
    const shared = await shareContent({
      title: l.shoppingList,
      text: generateListText().replace(/\*/g, "")
    });
    if (!shared) handleCopy();
  };

  return (
    <Sheet open={open} onOpenChange={onClose}>
      <SheetContent side="bottom" className="rounded-t-3xl p-0">
        <SheetHeader className="border-b border-gray-200 px-6 py-4">
          <SheetTitle className="flex items-center gap-2 text-lg font-bold">
            <Share2 className="h-5 w-5 text-primary" />
            {l.title}
          </SheetTitle>
        </SheetHeader>
        <div className="space-y-4 px-6 py-5 pb-8">
          <div className="max-h-48 overflow-auto rounded-md bg-muted/50 p-4">
            <pre className="whitespace-pre-wrap text-xs text-foreground">
              {generateListText().replace(/\*/g, "")}
            </pre>
          </div>
          <div className="grid grid-cols-2 gap-3">
            <button
              onClick={handleCopy}
              className="flex flex-col items-center gap-2 rounded-md bg-white border border-gray-200 p-4 transition-all active:scale-95 hover:bg-muted"
            >
              {copied ? (
                <Check className="h-6 w-6 text-primary" />
              ) : (
                <Copy className="h-6 w-6 text-gray-500" />
              )}
              <span className="text-sm font-medium text-foreground">
                {copied ? l.copied : l.copy}
              </span>
            </button>
            <button
              onClick={handleWhatsApp}
              className="flex flex-col items-center gap-2 rounded-md bg-white border border-gray-200 p-4 transition-all active:scale-95 hover:bg-muted"
            >
              <MessageCircle className="h-6 w-6 text-green-500" />
              <span className="text-sm font-medium text-foreground">
                WhatsApp
              </span>
            </button>
            <button
              onClick={handleEmail}
              className="flex flex-col items-center gap-2 rounded-md bg-white border border-gray-200 p-4 transition-all active:scale-95 hover:bg-muted"
            >
              <Mail className="h-6 w-6 text-blue-500" />
              <span className="text-sm font-medium text-foreground">
                E-mail
              </span>
            </button>
            <button
              onClick={handleNativeShare}
              className="flex flex-col items-center gap-2 rounded-md bg-white border border-gray-200 p-4 transition-all active:scale-95 hover:bg-muted"
            >
              <Share2 className="h-6 w-6 text-primary" />
              <span className="text-sm font-medium text-foreground">
                {l.moreOptions}
              </span>
            </button>
          </div>
          <Button
            variant="outline"
            className="w-full gap-2 rounded-md"
            onClick={() => toast.info(l.qrSoon)}
          >
            <QrCode className="h-4 w-4" />
            {l.generateQR}
          </Button>
        </div>
      </SheetContent>
    </Sheet>
  );
}
